### ISSUE TITLE
Key stored in app is not secured

### ISSUE THREAD

**Issue by lensonsaldanha** [skavinvarnan/Cross-Platform-AES#17]
I know its not an issue, but I just wanted to know how can i store the key in android app, if someone tries to reverse engineer the app, they can get the key and easily decrypt the data.

**Comment by skavinvarnan** [comment]
Avoid saving it locally. Try to save on the server and always make HTTPS call. If you really want to save it locally try to encrypt the key on an iterative loop with complicated keys. 

Closing this ticket, since its not relevant.
