### ISSUE TITLE
How do I handle the error in node js?

### ISSUE THREAD

**Issue by lensonsaldanha** [skavinvarnan/Cross-Platform-AES#18]
Specially when I decrypt the data if i dont send the encrypted data instead send the plain text, the node js app crashes, how do I prevent it from crashing and send error response? I'm thinking what if the hacker sends plain text and the app crashes and uses this to crash the app again and again, help me with this as I am new to node js

**Comment by skavinvarnan** [comment]
Check for null string before you pass the string to the library
