### ISSUE TITLE
Some chars missing while decrypting in Android side!

### ISSUE THREAD

**Issue by vinuz86** [skavinvarnan/Cross-Platform-AES#21]
While decrypting cypher text in Android using 'decryptCipherTextWithRandomIV', which was received from Php side, shows only a part of actual data or some character is missing. After a few tries randomly get the exact plain text as desired! 
The code is mentioned below : 

String cipherText = "WelKD2g4ThgJPeRiVz5FCcMoZG9pGCGgSjDlkD2hq3ee1SRPovlia0o9dEBwpLjg";
String key = "1122334455667788";

String decryptedString = cryptLib.decryptCipherTextWithRandomIV(cipherText, key);

Which may produce the plain text with some letters missing sometimes!!!.. Please help out.

**Comment by skavinvarnan** [comment]
Please try out these [tests](https://github.com/skavinvarnan/Cross-Platform-AES#few-tests)

This way you can narrow down to find if the issue is with Android or PHP

**Comment by vinuz86** [comment]
@skavinvarnan Thankyou for your valuable suggestion. Yes I have checked those examples in both Android side and Php side which is working fine!! 
But in the same place while checking in the Php side,  decrypting the cypher text which was encrypted from php side itself works fine and receives the output. Also can decrypt the cypherText from Android side successfully.
So im confused in this scenerio. Expecting your valuable comments.

**Comment by skavinvarnan** [comment]
When you say some part is missing, can you confirm the character count. Is it 16?

**Comment by vinuz86** [comment]
String key = "1122334455667788";
(Actual cypher text val --> "Hello wolrd 2019")
String cipherText ="WelKD2g4ThgJPeRiVz5FCcMoZG9pGCGgSjDlkD2hq3ee1SRPovlia0o9dEBwpLjg";

But while decrypting('decryptCipherTextWithRandomIV') the same thing repeatedly in Android side, the following is the output >>
First attempt --> ello wolrd 2019
Second attempt --> o wolrd 2019
Third attempt --> Hello wolrd 2019 (_which is the correct one_)
Fourth attempt --> o wolrd 2019

It goes like that, as the real desired result may miss some letters, one or two!

**Comment by skavinvarnan** [comment]
I guess there is a problem with PHP encoding. Will do the investigation. Meanwhile can you try using Javascript library?

Attaching screenshot of the issue 
![Screenshot 2019-03-16 at 12 35 34 PM](https://user-images.githubusercontent.com/5348524/54472048-3ba27c80-47e8-11e9-8aef-59dda9313502.png)

**Comment by vinuz86** [comment]
Presently we cant use Javascipt lib as this was for an API purpose.
 Can u suggest any changes in PHP side encryption, if it is the case of  problem with PHP encoding.
Looking forward for your positive reply.

**Comment by skavinvarnan** [comment]
Contribution to the PHP library was done by @ahsankhatri
I need to check in all the platform before confirming the issue. 

@vinuz86 It will take atleast a week to fix this issue.

**Comment by vinuz86** [comment]
@skavinvarnan Ok thankyou, will wait for your reply.

**Comment by sreejithvivk** [comment]
Whether this issue sorted out..Or still have this issue while decrypting in android / ios

**Comment by sreejithvivk** [comment]
Any truncation issue exists while decrypting with android / ios

**Comment by skavinvarnan** [comment]
There is no issue on ios / android decryption and encryption

**Comment by sreejithvivk** [comment]
Thanks you for the reply...But it seems some letters are been truncated when decrypting using android....we are using the secret key and the IV is random.

**Comment by skavinvarnan** [comment]
The root cause of that is because of encrypting on PHP and decrypt in Android. 

Between android and ios it works fine

**Comment by sreejithvivk** [comment]
We are encrypting the API in PHP and trying to decrypt the values using Android / ios..

**Comment by skavinvarnan** [comment]
That doesn't work reliable. I would recommend to use Javascript

**Comment by sreejithvivk** [comment]
But we have to encrypt our date using PHP only...Since we are using the API for fetching the data and pass them as json response

**Comment by skavinvarnan** [comment]
Do a basic regression test before you can depend so much on this library.

**Comment by ahsankhatri** [comment]
Let me have a look on PHP library.

**Comment by sreejithvivk** [comment]
We are creating the APIs using PHP and android / ios part is done by another team where we don't have the flexibility to check the decryption ...We have tested using Postman and worked perfect..So we relied on the library and gave to android team...Decryption issues identified when they have used it. Some parts of  the strings been truncated....

**Comment by sreejithvivk** [comment]
Any updates on the above issue please?

**Comment by sreejithvivk** [comment]
Any updates on the above issue please?

**Comment by sreejithvivk** [comment]
API field encrypted using Laravel is giving different results when decrypting using android / ios.  The field name is  "Emma" and in 5 calls while decrypting, receives "em", "emm", "ma", "Emma" and "ma". Kindly look in to the issue

**Comment by ahsankhatri** [comment]
The issue with was random IV generator, it was generating multi-byte character which caused problem while decrypting on other platform though it was working well with PHP. Please run `composer update`. I've just rollout `v1.1.0`.

**Comment by sreejithvivk** [comment]
Thanks You for looking in to the issue...
