### ISSUE TITLE
 Decryption is not working with swift IOS

### ISSUE THREAD

**Issue by sadhu-sanjay** [skavinvarnan/Cross-Platform-AES#24]
Could you please check the IOS Decryption and Encryption it not working Properly. when I'am trying to decrypt a string which was encrypted on Android platform.
(or could be please remove CrossPlatform from the title..its misleading) Sorry for my Langauge.

**Comment by skavinvarnan** [comment]
I tried with the example given [here](https://github.com/skavinvarnan/Cross-Platform-AES#ios--swift-3-4). It works fine. 

Environment tested:
xcode: 10.12.1
simulator: iPhone XR iOS 12

**Comment by sadhu-sanjay** [comment]
Sorry..i may have jumped the Gun. its working, if we go by the examples.  Turns out the guys on android side are using https://github.com/Pakhee/Cross-platform-AES-encryption
which i believe is the base code for your library. hence the confusion 
                                        Anyways..thanks

**Comment by skavinvarnan** [comment]
No problem.
