### ISSUE TITLE
Decryption is not working properly

### ISSUE THREAD

**Issue by AltafRehman** [skavinvarnan/Cross-Platform-AES#25]
I am using `encryptPlainText`/`decryptCipherText` functions for encryption/decryption. Encryption is working fine but decryption gives wrong result. 

> "#\"S7\u{1F}\u{0B}03vB!\'+c\n]\"Message\":\"\",\"ErrorNumber\":0,\"UserInfo\":{\"UserDetails\":[]}"

> 
But I expect a correct JSON. 

I tried tried tried many things and at last I figure out the issue. The issue is in your objective c file. In `decryptCipherText` method we pass iv in argument but you generate random iv. 

`- (NSString *) decryptCipherText:(NSString *)ciperText key:(NSString *)key iv:(NSString *)iv {
    return [[NSString alloc] initWithData:[[CryptLib alloc] decrypt:[[NSData alloc] initWithBase64EncodedString:ciperText options:NSDataBase64DecodingIgnoreUnknownCharacters] key:[[CryptLib alloc] sha256:key length:32] iv:[[CryptLib alloc] generateRandomIV16]] encoding:NSUTF8StringEncoding];
}`

Please replace the above method with following

`- (NSString *) decryptCipherText:(NSString *)ciperText key:(NSString *)key iv:(NSString *)iv {
    return [[NSString alloc] initWithData:[[CryptLib alloc] decrypt:[[NSData alloc] initWithBase64EncodedString:ciperText options:NSDataBase64DecodingIgnoreUnknownCharacters] key:[[CryptLib alloc] sha256:key length:32] iv:iv] encoding:NSUTF8StringEncoding];
}`

**Comment by skavinvarnan** [comment]
This issue has been fixed
