### ISSUE TITLE
Encryption failing for cross-platform use.

### ISSUE THREAD

**Issue by aarons2222** [skavinvarnan/Cross-Platform-AES#28]
I've created a sample project for testing. I encrypt a string with Obj-c and attempt to decrypt it on using Android. I'm able to Decrypt the string on iOS but not Android. Any help would be greatly appreciated...  Many thanks     I receive a 'bad padding exception'

Obj-C Code: 

        NSString *plainText = @"this is my plain text";
        NSString *keyy = @"simplekey";
        NSString *iiv = @"1234123412341234";
       
        NSString *encryptedString = [[CryptLib alloc] encryptPlainText:plainText key:keyy iv:iiv];

**Comment by Dararii** [comment]
same issue here.

**Comment by mrazam110** [comment]
Same issue

**Comment by octalanil1** [comment]
Same issue

**Comment by aarons2222** [comment]
> Issue Happen only in iOS13

no, iOS 11 and 12 also

**Comment by skavinvarnan** [comment]
This issue has been fixed
