### ISSUE TITLE
Bad cryptography, no understanding of encoding

### ISSUE THREAD

**Issue by owlstead** [skavinvarnan/Cross-Platform-AES#3]
This is just a **bad** implementation of AES with CBC and PKCS#7 padding. Basically it is a single call to CCCrypt where **all** the parameters are abused.

In my opinion this whole library should be marked deprecated with the utmost urgency. There is nothing worth saving here (except possibly the data of the persons using this library: otherwise I would have recommended full out destruction).

It clearly shows lack of understanding of cryptography and encoding at the most basic levels. For instance, it confuses passwords with keys. An IV is not a string either. Buffer sizes are miscalculated (fortunately they are made larger than required instead of smaller). Error numbers may be ignored, for instance during IV generation. The IV is not prefixed to the ciphertext.

As an example, don't expect it to actually use your key data as key. It may (or may not, depending on which function you call) perform a SHA-256 over the key **string** (see what I mean) encoded in ASCII. Then it will encode it to hexadecimals and use the 32 **hexadecimal digits**, encoded to UTF-8 as key, basically halving your "key" size in one easy step.

I've included a review of the code. 

USE THIS LIBRARY AND YOU MAY LOOSE YOUR DATA

[review_mb.txt](https://github.com/skavinvarnan/Cross-Platform-AES/files/1033451/review_mb.txt)

Oh, I'm [this guy](https://stackoverflow.com/users/589259), 16 years of continuous experience in the field.

**Comment by skavinvarnan** [comment]
@owlstead I'm not a cryptography guy. I have taken libraries from Android/iOS and Javascript. 

I have just written an example to make it work across all the 3 platforms. May be you can help me code better and i'll be happy to do those changes to the library
