### ISSUE TITLE
iOS 13 Decryption failure

### ISSUE THREAD

**Issue by wtdu** [skavinvarnan/Cross-Platform-AES#32]
On iOS 13 devices, Handling decryption with the library's encrypted strings has consistently failed

**Comment by ahsanghauri** [comment]
#29 please go through this

**Comment by arvind8192** [comment]
If decryption is not working than look into
1.  last commit by developer.
2. I solved above issue by replacing 
 NSString *hash=[out description];  with   NSString *hash=[out debugDescription]; 
Now it is working fine.
Sorry for any mistake this is my first comment.

**Comment by IanPhilips** [comment]
https://stackoverflow.com/questions/58098958/aes-encryption-cryptlib-in-ios-13-not-working

**Comment by shapljts** [comment]
This was causing an issue for us with cross-platform iOS/Android and @arvind8192 's solution fixed it for us.

**Comment by skavinvarnan** [comment]
This issue has been fixed
