### ISSUE TITLE
how to do it in PHP

### ISSUE THREAD

**Issue by jayaryan** [skavinvarnan/Cross-Platform-AES#5]
how to do it in PHP ?

**Comment by skavinvarnan** [comment]
@jayaryan My code base doesn't have PHP example. Will add this to the roadmap.

**Comment by manojnetsmartz** [comment]
@skavinvarnan, can you please suggest, how can I use Cross-Platform-AES in PHP, any php example?

**Comment by skavinvarnan** [comment]
@manojnetsmartz PHP not will be part of the roadmap. Sorry about that. You could use Javascript if that work for you.
