### ISSUE TITLE
Need encryption decryption in Node JS for Files (Images, Text Files)

### ISSUE THREAD

**Issue by vikranttrantor** [skavinvarnan/Cross-Platform-AES#9]
Hello Sir,

I need code for encryption decryption in Node JS for Files (Images, Text Files) using your code. 

Please help me out. 

Regards,
Vikrant

**Comment by skavinvarnan** [comment]
The code doesn't not support it. As this library only does encryption and decryption of String.

If you see the source code of the library lets say android [code](https://github.com/skavinvarnan/Cross-Platform-AES/blob/master/Android/CryptLib.java#L146). I convert the passed string to bytes and then do encryption or decryption. 

You have to make changes to library. All you have to do is convert your image or text file to bytes and then you are all good to go with encryption and decryption
